### ISSUE TITLE
Show outstanding security updates 

### ISSUE THREAD

**Issue by adamshand** [bderenzo/tinymotd#2]
Hey,

I thought this was a bit gimmicky at first, but installed it on my home server and really liked it.  So now it's installed on all my servers, thanks! :-)

One thing that would be nice is if the apt module displayed the number of outstanding security updates as well. For anyone running Debian Stable you can get this number with this query:

`apt-get upgrade --dry-run | awk '/Debian-Security/ {print $2}' | sort -u | wc -l`

Not sure how to get it for Debian Testing or Unstable but trying to figure it out.

**Comment by ServerGeek82** [comment]
+1 for this

**Comment by bderenzo** [comment]
I've implemented this feature.
