### ISSUE TITLE
Network widget, wrong IP ?

### ISSUE THREAD

**Issue by robinmensch** [bderenzo/tinymotd#8]
Hello,

Thank you so much for this amazing script.

I have an issue, the network widget doesn't show me my real public IP, but an IP of the openDNS resolver.
The private part is ok.

Any solution ?

Thanks,

Robin

**Comment by adRn-s** [comment]
Do you get a correct IP using `ip route | grep default`?

PS. To the author of this repo: that's how [i3blocks community](https://github.com/vivien/i3blocks-contrib/blob/master/iface/iface) retrieves IP, for the i3wm status bar.

**Comment by robinmensch** [comment]
`ip route | grep default` give me the server's private IP, via the IP of my internet provider router.

**Edit:** I tried the old code for line 14:  `publicip=$(dig +short myip.opendns.com @resolver1.opendns.com)` and installed dnsutils.

It works.

**Comment by bderenzo** [comment]
Thank you for reporting the problem. I have corrected the public IP retrieval. 
@adRn-s i3blocks code seems to retrieve only the private IP.
