### ISSUE TITLE
docker widget

### ISSUE THREAD

**Issue by adRn-s** [bderenzo/tinymotd#9]
`$ docker ps -a --format "{{.Names}} {{.State}}"` returns "running" for my containers. This is what the widget uses as command.

meanwhile, `$ docker ps -a --format "{{.Names}} {{.Status}}"` returns "Up N days". This is what the widget expects as call to `c_match_r`.

Btw, `$ docker -v` is `Docker version 25.0.4, build 1a576c5` and I'm running a debian-based distro.

PS: nice work!

**Comment by bderenzo** [comment]
Thank you for reporting the problem. I have corrected the container status presentation.
